services:
  api:
    build: .
    container_name: api
    command: dev
    working_dir: /backend
    volumes:
      - .:/backend
      - /backend/node_modules
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    env_file:
      - .env
    tty: true
    stdin_open: true
    restart: always
  db:
    image: postgres
    shm_size: 128mb
    platform: linux/x86_64
    restart: always
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env.db
    volumes:
    - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      timeout: 10s
      retries: 5